# Generated by Django 6.0.1 on 2026-02-02 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petrolera', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AreaSegura',
        ),
        migrations.DeleteModel(
            name='Factura',
        ),
        migrations.AddField(
            model_name='pozo',
            name='ubicacion',
            field=models.CharField(default='Sin ubicación asignada', max_length=100),
        ),
        migrations.AlterField(
            model_name='perfilempleado',
            name='cargo',
            field=models.CharField(choices=[('TECNICO', 'Técnico de Campo'), ('SEGURIDAD', 'Seguridad Física'), ('ADMIN', 'Administrador/Gerente')], default='TECNICO', max_length=20),
        ),
        migrations.AlterField(
            model_name='pozo',
            name='barriles_diarios',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
